### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [google/or-tools#2434]
... 
-- Installing: /data/jw/or-tools/dependencies/install/lib64/cmake/protobuf/protobuf-config-version.cmake
-- Installing: /data/jw/or-tools/dependencies/install/lib64/cmake/protobuf/protobuf-module.cmake
-- Installing: /data/jw/or-tools/dependencies/install/lib64/cmake/protobuf/protobuf-options.cmake
gmake[1]: Leaving directory '/data/jw/or-tools/dependencies/sources/protobuf-v3.15.3/build_cmake'
cd dependencies/sources/CoinUtils-2.11.4 &&  ./configure \
    --prefix=/data/jw/or-tools/dependencies/install \
    --enable-static --disable-shared \
    --disable-bzlib \
    --disable-debug \
    --without-blas \
    --without-lapack \
    --without-glpk \
    --with-pic \
    --disable-dependency-tracking \
    --enable-dependency-linking \
    ADD_CXXFLAGS="-w  -std=c++11"
checking build system type... ./config.guess: unable to guess system type

This script, last modified 2007-05-17, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess
and
  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2007-05-17

uname -m = aarch64
uname -r = 5.10.13-200.fc33.aarch64
uname -s = Linux
uname -v = #1 SMP Thu Feb 4 14:41:02 UTC 2021

/usr/bin/uname -p = aarch64
/bin/uname -X     =

hostinfo               =
/bin/universe          =
/usr/bin/arch -k       =
/bin/arch              = aarch64
/usr/bin/oslevel       =
/usr/convex/getsysinfo =

UNAME_MACHINE = aarch64
UNAME_RELEASE = 5.10.13-200.fc33.aarch64
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP Thu Feb 4 14:41:02 UTC 2021
configure: error: cannot guess build type; you must specify one
make: *** [makefiles/Makefile.third_party.unix.mk:551: dependencies/install/lib/libCoinUtils.a] Error 1
[jw@cn06 or-tools]$ 

In this case, 'configure' should be called with '--build=aarch64-unknown-linux-gnu'.

**Comment by Mizux** [comment]
Can you try the CMake based build instead ?

**Comment by LutzWeischerFujitsu** [comment]
[jw@cn05 build]$ cmake ..
-- ortools version: 8.2.8710
-- Build C++ library: ON
-- Build Python: OFF
-- Build Java: OFF
-- Build .Net: OFF
-- Build Flatzinc: ON
-- Build standalone Glop: OFF
-- Build samples: ON
-- Build C++ samples: ON
-- Build Python samples: OFF
-- Build Java samples: OFF
-- Build .Net samples: OFF
-- Build examples: ON
-- Build C++ examples: ON
-- Build Python examples: OFF
-- Build Java examples: OFF
-- Build .Net examples: OFF
-- Build all dependencies: OFF
-- Build ZLIB: OFF
-- Build abseil-cpp: OFF
-- Build protobuf: OFF
-- SCIP support: ON
-- Build SCIP: OFF
-- COIN-OR support: ON
-- Build CoinUtils: OFF
-- Build Osi: OFF
-- Build Clp: OFF
-- Build Cgl: OFF
-- Build Cbc: OFF
-- CPLEX support: OFF
-- XPRESS support: OFF
-- Found long size: 8
-- Found long long size: 8
-- Found int64_t size: 8
-- Found unsigned long size: 8
-- Found unsigned long long size: 8
-- Found uint64_t size: 8
-- Found int * size: 8
CMake Error at cmake/deps.cmake:20 (find_package):
  By not providing "Findabsl.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "absl", but
  CMake did not find one.

  Could not find a package configuration file provided by "absl" with any of
  the following names:

    abslConfig.cmake
    absl-config.cmake

  Add the installation prefix of "absl" to CMAKE_PREFIX_PATH or set
  "absl_DIR" to a directory containing one of the above files.  If "absl"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:235 (include)

-- Configuring incomplete, errors occurred!
See also "/home/jw/or-tools/build/CMakeFiles/CMakeOutput.log".
See also "/home/jw/or-tools/build/CMakeFiles/CMakeError.log".
[jw@cn05 build]$

**Comment by Mizux** [comment]
You need to use `-DBUILD_DEPS=ON` 
more info in the cmake directory
See https://github.com/google/or-tools/blob/stable/cmake/README.md

**Comment by LutzWeischerFujitsu** [comment]
Thanks. To build it I used now 

cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DBUILD_DEPS=ON -DBUILD_PYTHON=ON -DBUILD_DOTNET=ON -DBUILD_JAVA=ON ..

However, the tests often fail: 

[jw@cn05 build]$ cmake --build build --target test
Running tests...
Test project /home/jw/or-tools/build/build
        Start   1: pytest_venv
  1/607 Test   #1: pytest_venv ................................................................   Passed    0.47 sec
        Start   2: java_tests_Test
  2/607 Test   #2: java_tests_Test ............................................................***Failed    9.65 sec
        Start   3: cxx_algorithms_knapsack
  3/607 Test   #3: cxx_algorithms_knapsack ....................................................   Passed    0.03 sec
        Start   4: cxx_algorithms_simple_knapsack_program
  4/607 Test   #4: cxx_algorithms_simple_knapsack_program .....................................   Passed    0.03 sec
        Start   5: python_algorithms_knapsack
  5/607 Test   #5: python_algorithms_knapsack .................................................   Passed    0.18 sec
        Start   6: python_algorithms_simple_knapsack_program
  6/607 Test   #6: python_algorithms_simple_knapsack_program ..................................   Passed    0.18 sec
        Start   7: java_algorithms_Knapsack
  7/607 Test   #7: java_algorithms_Knapsack ...................................................***Failed    6.45 sec
        Start   8: dotnet_algorithms_Knapsack
  8/607 Test   #8: dotnet_algorithms_Knapsack .................................................***Failed    3.59 sec
        Start   9: cxx_graph_simple_max_flow_program
  9/607 Test   #9: cxx_graph_simple_max_flow_program ..........................................   Passed    0.03 sec
        Start  10: cxx_graph_simple_min_cost_flow_program
 10/607 Test  #10: cxx_graph_simple_min_cost_flow_program .....................................   Passed    0.03 sec
        Start  11: python_graph_simple_max_flow_program
 11/607 Test  #11: python_graph_simple_max_flow_program .......................................   Passed    0.18 sec
        Start  12: python_graph_simple_min_cost_flow_program
 12/607 Test  #12: python_graph_simple_min_cost_flow_program ..................................   Passed    0.18 sec
        Start  13: dotnet_graph_SimpleMaxFlowProgram
 13/607 Test  #13: dotnet_graph_SimpleMaxFlowProgram ..........................................***Failed    3.58 sec
        Start  14: dotnet_graph_SimpleMinCostFlowProgram
 14/607 Test  #14: dotnet_graph_SimpleMinCostFlowProgram ......................................***Failed    3.62 sec
        Start  15: cxx_linear_solver_assignment_mip
 15/607 Test  #15: cxx_linear_solver_assignment_mip ...........................................   Passed    0.07 sec
        Start  16: cxx_linear_solver_basic_example
 16/607 Test  #16: cxx_linear_solver_basic_example ............................................   Passed    0.03 sec
        Start  17: cxx_linear_solver_bin_packing_mip
 17/607 Test  #17: cxx_linear_solver_bin_packing_mip ..........................................   Passed    0.09 sec
        Start  18: cxx_linear_solver_integer_programming_example
 18/607 Test  #18: cxx_linear_solver_integer_programming_example ..............................   Passed    0.07 sec
        Start  19: cxx_linear_solver_linear_programming_example
 19/607 Test  #19: cxx_linear_solver_linear_programming_example ...............................   Passed    0.03 sec
        Start  20: cxx_linear_solver_mip_var_array
 20/607 Test  #20: cxx_linear_solver_mip_var_array ............................................   Passed    0.14 sec
        Start  21: cxx_linear_solver_multiple_knapsack_mip
 21/607 Test  #21: cxx_linear_solver_multiple_knapsack_mip ....................................   Passed    0.26 sec
        Start  22: cxx_linear_solver_simple_lp_program
 22/607 Test  #22: cxx_linear_solver_simple_lp_program ........................................   Passed    0.03 sec
        Start  23: cxx_linear_solver_simple_mip_program
 23/607 Test  #23: cxx_linear_solver_simple_mip_program .......................................   Passed    0.07 sec
        Start  24: python_linear_solver_assignment_mip
 24/607 Test  #24: python_linear_solver_assignment_mip ........................................   Passed    0.24 sec
        Start  25: python_linear_solver_basic_example
 25/607 Test  #25: python_linear_solver_basic_example .........................................   Passed    0.19 sec
        Start  26: python_linear_solver_bin_packing_mip
 26/607 Test  #26: python_linear_solver_bin_packing_mip .......................................   Passed    0.28 sec
        Start  27: python_linear_solver_integer_programming_example
 27/607 Test  #27: python_linear_solver_integer_programming_example ...........................   Passed    0.24 sec
        Start  28: python_linear_solver_linear_programming_example
 28/607 Test  #28: python_linear_solver_linear_programming_example ............................   Passed    0.19 sec
        Start  29: python_linear_solver_mip_var_array
 29/607 Test  #29: python_linear_solver_mip_var_array .........................................   Passed    0.30 sec
        Start  30: python_linear_solver_multiple_knapsack_mip
 30/607 Test  #30: python_linear_solver_multiple_knapsack_mip .................................   Passed    0.44 sec
        Start  31: python_linear_solver_simple_lp_program
 31/607 Test  #31: python_linear_solver_simple_lp_program .....................................   Passed    0.19 sec
        Start  32: python_linear_solver_simple_mip_program
 32/607 Test  #32: python_linear_solver_simple_mip_program ....................................   Passed    0.23 sec
        Start  33: java_linear_solver_AssignmentMip
 33/607 Test  #33: java_linear_solver_AssignmentMip ...........................................***Failed    6.33 sec
        Start  34: java_linear_solver_BasicExample
 34/607 Test  #34: java_linear_solver_BasicExample ............................................***Failed    6.09 sec
        Start  35: java_linear_solver_BinPackingMip
 35/607 Test  #35: java_linear_solver_BinPackingMip ...........................................***Failed    6.18 sec
        Start  36: java_linear_solver_LinearProgrammingExample
 36/607 Test  #36: java_linear_solver_LinearProgrammingExample ................................***Failed    6.24 sec
        Start  37: java_linear_solver_MipVarArray
 37/607 Test  #37: java_linear_solver_MipVarArray .............................................***Failed    6.11 sec
        Start  38: java_linear_solver_MultipleKnapsackMip
 38/607 Test  #38: java_linear_solver_MultipleKnapsackMip .....................................***Failed    6.21 sec
        Start  39: java_linear_solver_SimpleLpProgram
 39/607 Test  #39: java_linear_solver_SimpleLpProgram .........................................***Failed    5.92 sec
        Start  40: java_linear_solver_SimpleMipProgram
 40/607 Test  #40: java_linear_solver_SimpleMipProgram ........................................***Failed    6.12 sec
        Start  41: dotnet_linear_solver_AssignmentMip
 41/607 Test  #41: dotnet_linear_solver_AssignmentMip .........................................***Failed    3.80 sec
        Start  42: dotnet_linear_solver_BasicExample
 42/607 Test  #42: dotnet_linear_solver_BasicExample ..........................................***Failed    3.58 sec
        Start  43: dotnet_linear_solver_BinPackingMip
 43/607 Test  #43: dotnet_linear_solver_BinPackingMip .........................................***Failed    3.61 sec
        Start  44: dotnet_linear_solver_LinearProgrammingExample
 44/607 Test  #44: dotnet_linear_solver_LinearProgrammingExample ..............................***Failed    3.68 sec
        Start  45: dotnet_linear_solver_MipVarArray
 45/607 Test  #45: dotnet_linear_solver_MipVarArray ...........................................***Failed    3.60 sec
        Start  46: dotnet_linear_solver_MultipleKnapsackMip
 46/607 Test  #46: dotnet_linear_solver_MultipleKnapsackMip ...................................***Failed    3.61 sec
        Start  47: dotnet_linear_solver_SimpleLpProgram
 47/607 Test  #47: dotnet_linear_solver_SimpleLpProgram .......................................***Failed    3.60 sec
        Start  48: dotnet_linear_solver_SimpleMipProgram
 48/607 Test  #48: dotnet_linear_solver_SimpleMipProgram ......................................***Failed    3.61 sec
        Start  49: cxx_constraint_solver_minimal_jobshop_cp
 49/607 Test  #49: cxx_constraint_solver_minimal_jobshop_cp ...................................   Passed    0.04 sec
        Start  50: cxx_constraint_solver_nurses_cp
 50/607 Test  #50: cxx_constraint_solver_nurses_cp ............................................   Passed    3.49 sec
        Start  51: cxx_constraint_solver_rabbits_and_pheasants_cp
 51/607 Test  #51: cxx_constraint_solver_rabbits_and_pheasants_cp .............................   Passed    0.03 sec
        Start  52: cxx_constraint_solver_simple_cp_program
 52/607 Test  #52: cxx_constraint_solver_simple_cp_program ....................................   Passed    0.03 sec
        Start  53: cxx_constraint_solver_simple_ls_program
 53/607 Test  #53: cxx_constraint_solver_simple_ls_program ....................................   Passed    0.04 sec
        Start  54: cxx_constraint_solver_simple_routing_program
 54/607 Test  #54: cxx_constraint_solver_simple_routing_program ...............................   Passed    0.04 sec
        Start  55: cxx_constraint_solver_tsp
 55/607 Test  #55: cxx_constraint_solver_tsp ..................................................   Passed    0.04 sec
        Start  56: cxx_constraint_solver_tsp_circuit_board
 56/607 Test  #56: cxx_constraint_solver_tsp_circuit_board ....................................   Passed    1.35 sec
        Start  57: cxx_constraint_solver_tsp_cities
 57/607 Test  #57: cxx_constraint_solver_tsp_cities ...........................................   Passed    0.04 sec
        Start  58: cxx_constraint_solver_tsp_cities_routes
 58/607 Test  #58: cxx_constraint_solver_tsp_cities_routes ....................................   Passed    0.04 sec
        Start  59: cxx_constraint_solver_tsp_distance_matrix
 59/607 Test  #59: cxx_constraint_solver_tsp_distance_matrix ..................................   Passed    0.04 sec
        Start  60: cxx_constraint_solver_vrp
 60/607 Test  #60: cxx_constraint_solver_vrp ..................................................   Passed    0.05 sec
        Start  61: cxx_constraint_solver_vrp_capacity
 61/607 Test  #61: cxx_constraint_solver_vrp_capacity .........................................   Passed    1.04 sec
        Start  62: cxx_constraint_solver_vrp_drop_nodes
 62/607 Test  #62: cxx_constraint_solver_vrp_drop_nodes .......................................   Passed    1.04 sec
        Start  63: cxx_constraint_solver_vrp_global_span
 63/607 Test  #63: cxx_constraint_solver_vrp_global_span ......................................   Passed    0.10 sec
        Start  64: cxx_constraint_solver_vrp_initial_routes
 64/607 Test  #64: cxx_constraint_solver_vrp_initial_routes ...................................   Passed    0.08 sec
        Start  65: cxx_constraint_solver_vrp_pickup_delivery
 65/607 Test  #65: cxx_constraint_solver_vrp_pickup_delivery ..................................   Passed    0.10 sec
        Start  66: cxx_constraint_solver_vrp_pickup_delivery_fifo
 66/607 Test  #66: cxx_constraint_solver_vrp_pickup_delivery_fifo .............................   Passed    0.09 sec
        Start  67: cxx_constraint_solver_vrp_pickup_delivery_lifo
 67/607 Test  #67: cxx_constraint_solver_vrp_pickup_delivery_lifo .............................   Passed    0.08 sec
        Start  68: cxx_constraint_solver_vrp_resources
 68/607 Test  #68: cxx_constraint_solver_vrp_resources ........................................   Passed    0.70 sec
        Start  69: cxx_constraint_solver_vrp_routes
 69/607 Test  #69: cxx_constraint_solver_vrp_routes ...........................................   Passed    0.05 sec
        Start  70: cxx_constraint_solver_vrp_starts_ends
 70/607 Test  #70: cxx_constraint_solver_vrp_starts_ends ......................................   Passed    0.07 sec
        Start  71: cxx_constraint_solver_vrp_time_windows
 71/607 Test  #71: cxx_constraint_solver_vrp_time_windows .....................................   Passed    0.05 sec
        Start  72: cxx_constraint_solver_vrp_with_time_limit
 72/607 Test  #72: cxx_constraint_solver_vrp_with_time_limit ..................................   Passed   10.04 sec
        Start  73: cxx_constraint_solver_vrptw_store_solution_data
 73/607 Test  #73: cxx_constraint_solver_vrptw_store_solution_data ............................   Passed    0.05 sec
        Start  74: python_constraint_solver_cvrp
 74/607 Test  #74: python_constraint_solver_cvrp ..............................................   Passed    1.46 sec
        Start  75: python_constraint_solver_cvrp_reload
 75/607 Test  #75: python_constraint_solver_cvrp_reload .......................................   Passed    3.44 sec
        Start  76: python_constraint_solver_cvrptw
 76/607 Test  #76: python_constraint_solver_cvrptw ............................................   Passed    4.38 sec
        Start  77: python_constraint_solver_cvrptw_break
 77/607 Test  #77: python_constraint_solver_cvrptw_break ......................................***Exception: SegFault  0.82 sec
        Start  78: python_constraint_solver_simple_cp_program
 78/607 Test  #78: python_constraint_solver_simple_cp_program .................................   Passed    0.22 sec
        Start  79: python_constraint_solver_simple_routing_program
 79/607 Test  #79: python_constraint_solver_simple_routing_program ............................   Passed    0.42 sec
        Start  80: python_constraint_solver_tsp
 80/607 Test  #80: python_constraint_solver_tsp ...............................................   Passed    0.45 sec
        Start  81: python_constraint_solver_tsp_circuit_board
 81/607 Test  #81: python_constraint_solver_tsp_circuit_board .................................   Passed   17.67 sec
        Start  82: python_constraint_solver_tsp_cities
 82/607 Test  #82: python_constraint_solver_tsp_cities ........................................   Passed    0.45 sec
        Start  83: python_constraint_solver_tsp_distance_matrix
 83/607 Test  #83: python_constraint_solver_tsp_distance_matrix ...............................   Passed    0.46 sec
        Start  84: python_constraint_solver_vrp
 84/607 Test  #84: python_constraint_solver_vrp ...............................................   Passed    0.50 sec
        Start  85: python_constraint_solver_vrp_capacity
 85/607 Test  #85: python_constraint_solver_vrp_capacity ......................................   Passed    1.42 sec
        Start  86: python_constraint_solver_vrp_drop_nodes
 86/607 Test  #86: python_constraint_solver_vrp_drop_nodes ....................................   Passed    1.42 sec
        Start  87: python_constraint_solver_vrp_global_span
 87/607 Test  #87: python_constraint_solver_vrp_global_span ...................................   Passed    0.93 sec
        Start  88: python_constraint_solver_vrp_initial_routes
 88/607 Test  #88: python_constraint_solver_vrp_initial_routes ................................   Passed    0.78 sec
        Start  89: python_constraint_solver_vrp_pickup_delivery
 89/607 Test  #89: python_constraint_solver_vrp_pickup_delivery ...............................   Passed    0.95 sec
        Start  90: python_constraint_solver_vrp_pickup_delivery_fifo
 90/607 Test  #90: python_constraint_solver_vrp_pickup_delivery_fifo ..........................   Passed    0.85 sec
        Start  91: python_constraint_solver_vrp_pickup_delivery_lifo
 91/607 Test  #91: python_constraint_solver_vrp_pickup_delivery_lifo ..........................   Passed    0.82 sec
        Start  92: python_constraint_solver_vrp_resources
 92/607 Test  #92: python_constraint_solver_vrp_resources .....................................   Passed    2.46 sec
        Start  93: python_constraint_solver_vrp_starts_ends
 93/607 Test  #93: python_constraint_solver_vrp_starts_ends ...................................   Passed    0.65 sec
        Start  94: python_constraint_solver_vrp_time_windows
 94/607 Test  #94: python_constraint_solver_vrp_time_windows ..................................   Passed    0.55 sec
        Start  95: python_constraint_solver_vrp_tokens
 95/607 Test  #95: python_constraint_solver_vrp_tokens ........................................   Passed    1.42 sec
        Start  96: python_constraint_solver_vrp_with_time_limit
 96/607 Test  #96: python_constraint_solver_vrp_with_time_limit ...............................   Passed   10.41 sec
        Start  97: python_constraint_solver_vrpgs
 97/607 Test  #97: python_constraint_solver_vrpgs .............................................   Passed    0.92 sec
        Start  98: python_constraint_solver_vrptw_store_solution_data
 98/607 Test  #98: python_constraint_solver_vrptw_store_solution_data .........................   Passed    0.55 sec
        Start  99: java_constraint_solver_SimpleCpProgram
 99/607 Test  #99: java_constraint_solver_SimpleCpProgram .....................................***Failed    6.40 sec
        Start 100: java_constraint_solver_SimpleRoutingProgram
100/607 Test #100: java_constraint_solver_SimpleRoutingProgram ................................***Failed    6.05 sec
        Start 101: java_constraint_solver_Tsp
101/607 Test #101: java_constraint_solver_Tsp .................................................***Failed    6.20 sec
        Start 102: java_constraint_solver_TspCircuitBoard
102/607 Test #102: java_constraint_solver_TspCircuitBoard .....................................***Failed    6.26 sec
        Start 103: java_constraint_solver_TspCities
103/607 Test #103: java_constraint_solver_TspCities ...........................................***Failed    6.01 sec
        Start 104: java_constraint_solver_TspDistanceMatrix
104/607 Test #104: java_constraint_solver_TspDistanceMatrix ...................................***Failed    6.26 sec
        Start 105: java_constraint_solver_Vrp
105/607 Test #105: java_constraint_solver_Vrp .................................................***Failed    5.98 sec
        Start 106: java_constraint_solver_VrpCapacity
106/607 Test #106: java_constraint_solver_VrpCapacity .........................................***Failed    6.11 sec
        Start 107: java_constraint_solver_VrpDropNodes
107/607 Test #107: java_constraint_solver_VrpDropNodes ........................................***Failed    6.04 sec
        Start 108: java_constraint_solver_VrpGlobalSpan
108/607 Test #108: java_constraint_solver_VrpGlobalSpan .......................................***Failed    6.01 sec
        Start 109: java_constraint_solver_VrpInitialRoutes
109/607 Test #109: java_constraint_solver_VrpInitialRoutes ....................................***Failed    6.10 sec
        Start 110: java_constraint_solver_VrpPickupDelivery
110/607 Test #110: java_constraint_solver_VrpPickupDelivery ...................................***Failed    5.87 sec
        Start 111: java_constraint_solver_VrpPickupDeliveryFifo
111/607 Test #111: java_constraint_solver_VrpPickupDeliveryFifo ...............................***Failed    6.10 sec
        Start 112: java_constraint_solver_VrpPickupDeliveryLifo
112/607 Test #112: java_constraint_solver_VrpPickupDeliveryLifo ...............................***Failed    6.11 sec
        Start 113: java_constraint_solver_VrpResources
113/607 Test #113: java_constraint_solver_VrpResources ........................................***Failed    6.26 sec
        Start 114: java_constraint_solver_VrpStartsEnds
114/607 Test #114: java_constraint_solver_VrpStartsEnds .......................................***Failed    6.08 sec
        Start 115: java_constraint_solver_VrpTimeWindows
115/607 Test #115: java_constraint_solver_VrpTimeWindows ......................................***Failed    6.10 sec
        Start 116: java_constraint_solver_VrpWithTimeLimit
116/607 Test #116: java_constraint_solver_VrpWithTimeLimit ....................................***Failed    6.01 sec
        Start 117: dotnet_constraint_solver_SimpleCpProgram
117/607 Test #117: dotnet_constraint_solver_SimpleCpProgram ...................................***Failed    3.61 sec
        Start 118: dotnet_constraint_solver_SimpleRoutingProgram
118/607 Test #118: dotnet_constraint_solver_SimpleRoutingProgram ..............................***Failed    3.62 sec
        Start 119: dotnet_constraint_solver_Tsp
119/607 Test #119: dotnet_constraint_solver_Tsp ...............................................***Failed    3.59 sec
        Start 120: dotnet_constraint_solver_TspCircuitBoard
120/607 Test #120: dotnet_constraint_solver_TspCircuitBoard ...................................***Failed    3.56 sec
        Start 121: dotnet_constraint_solver_TspCities
121/607 Test #121: dotnet_constraint_solver_TspCities .........................................***Failed    3.59 sec
...

**Comment by nobodyinperson** [comment]
Same problem on Manjaro ARM aarch64 (on a Pinebook Pro) while building [`python-or-tools` from the AUR](https://aur.archlinux.org/packages/python-or-tools/).

To get `make third_party` to work, I had to update the `config.guess` and `config.sub` scripts as suggested in the error message:

```bash
wget http://savannah.gnu.org/cgi-bin/viewcvs/\*checkout\*/config/config/config.guess
wget http://savannah.gnu.org/cgi-bin/viewcvs/\*checkout\*/config/config/config.sub
# overwrite old broken scripts with new ones by symlinks
find -mindepth 2 -iname config.guess | while read f;do ln -rsf config.guess;done
find -mindepth 2 -iname config.sub  | while read f;do ln -rsf config.sub "$f";done
```

To get `make python` to work, I had to place a dirty symlink:

```bash
ln -rsf dependencies/install/lib/libtpinone-7.0.1.linux.{arm,x86_64}.gnu.opt.a
```

For some reason the `Makefile` (or something nested deeply within) expected an x86_64 version of that library...

After **hours** of compilation time I finally got the `python-or-tools` package built.

I need it as a dependency for [`flatcam-git`](https://aur.archlinux.org/packages/flatcam-git/) but unfortunately the `ortools` package still seems to be broken:

```python
[ins] In [4]: from ortools.constraint_solver import routing_enums_pb2
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-1a8045dd23d6> in <module>
----> 1 from ortools.constraint_solver import routing_enums_pb2

/usr/lib/python3.9/site-packages/ortools/constraint_solver/routing_enums_pb2.py in <module>
     19   syntax='proto3',
     20   serialized_options=b'\n#com.google.ortools.constraintsolverP\001\252\002\037Google.OrTools.ConstraintSolver',
---> 21   create_key=_descriptor._internal_create_key,
     22   serialized_pb=b'\n-ortools/constraint_solver/routing_enums.proto\x12\x13operations_research\"\x8c\x03\n\x15\x46irstSolutionStrategy\"\xf2\x02\n\x05Value\x12\t\n\x05UNSET\x10\x00\x12\r\n\tAUTOMATIC\x10\x0f\x12\x15\n\x11PATH_CHEAPEST_ARC\x10\x03\x12\x1d\n\x19PATH_MOST_CONSTRAINED_ARC\x10\x04\x12\x16\n\x12\x45VALUATOR_STRATEGY\x10\x05\x12\x0b\n\x07SAVINGS\x10\n\x12\t\n\x05SWEEP\x10\x0b\x12\x10\n\x0c\x43HRISTOFIDES\x10\r\x12\x13\n\x0f\x41LL_UNPERFORMED\x10\x06\x12\x12\n\x0e\x42\x45ST_INSERTION\x10\x07\x12\x1f\n\x1bPARALLEL_CHEAPEST_INSERTION\x10\x08\x12!\n\x1dSEQUENTIAL_CHEAPEST_INSERTION\x10\x0e\x12\x1c\n\x18LOCAL_CHEAPEST_INSERTION\x10\t\x12\x17\n\x13GLOBAL_CHEAPEST_ARC\x10\x01\x12\x16\n\x12LOCAL_CHEAPEST_ARC\x10\x02\x12\x1b\n\x17\x46IRST_UNBOUND_MIN_VALUE\x10\x0c\"\xae\x01\n\x18LocalSearchMetaheuristic\"\x91\x01\n\x05Value\x12\t\n\x05UNSET\x10\x00\x12\r\n\tAUTOMATIC\x10\x06\x12\x12\n\x0eGREEDY_DESCENT\x10\x01\x12\x17\n\x13GUIDED_LOCAL_SEARCH\x10\x02\x12\x17\n\x13SIMULATED_ANNEALING\x10\x03\x12\x0f\n\x0bTABU_SEARCH\x10\x04\x12\x17\n\x13GENERIC_TABU_SEARCH\x10\x05\x42I\n#com.google.ortools.constraintsolverP\x01\xaa\x02\x1fGoogle.OrTools.ConstraintSolverb\x06proto3'
     23 )

AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

Or maybe that's just another problem with `protobuf` then...

**Comment by lperron** [comment]
different protobuf versions used ?
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le sam. 10 avr. 2021 à 14:05, Yann Büchau ***@***.***> a
écrit :

**Comment by nobodyinperson** [comment]
Yes, updating `protobuf` helped. I already removed that part from my comment.

**Comment by Mizux** [comment]
Currently we only support C++ on AARCH64, I.e. we didn't do the support for ARM64 in the setup.py, pom.xml or .csproj ...

**Comment by szerfas1** [comment]
> Currently we only support C++ on AARCH64, I.e. we didn't do the support for ARM64 in the setup.py, pom.xml or .csproj

+1 to supporting building python wheels / setup.py for ARM64. I just spent a day or so working through build issues in hopes of building a Python wheel for ortools v7.7 to work on Ubuntu (18.04 for now, later versions soon), only to find here after I got it to build that there's no support to build the `setup.py` and build a wheel. Thanks for all your work maintaining the project; would love to see this supported when you can.

**Comment by nobodyinperson** [comment]
Same problem with the new v9.0, the same [solution](https://github.com/google/or-tools/issues/2434?_pjax=%23js-repo-pjax-container#issuecomment-817126196) lets the build continue.

**Comment by Mizux** [comment]
> To get `make python` to work, I had to place a dirty symlink:
> 
> ```shell
> ln -rsf dependencies/install/lib/libtpinone-7.0.1.linux.{arm,x86_64}.gnu.opt.a
> ```
> For some reason the `Makefile` (or something nested deeply within) expected an x86_64 version of that library...

seems related to this: https://github.com/LITICSoftware/or-tools/commit/f0421dbd0b8f6ede9561318fad662649f434f46b
