### ISSUE TITLE
Install issues OSX Sierra

### ISSUE THREAD

**Issue by bendichter** [google/or-tools#471]
Hi,

I am having some installation issues on OSX Sierra. I tried installing binary with conda envs with python = 2.7, 3.5, and 3.6. Each time I get `error: Could not find suitable distribution for Requirement.parse('ortools==6.3.4431')`. From the issues it looks like only El Capitan binaries are supported. Has this changed? The documentation claims that OSX 10.12 is supported, so I'm confused by this.

Anyway, I proceeded to try to install from source in python 2.7.
`make third_party`: no error
`make python`
...
`swig -I. -c++ -python  -o ortools/gen/ortools/constraint_solver/constraint_solver_python_wrap.cc -module pywrapcp ./ortools/constraint_solver/python/routing.i
ortools/constraint_solver/constraint_solver.h:1762: Error: Syntax error in input(3).
make: *** [ortools/gen/ortools/constraint_solver/pywrapcp.py] Error 1`

I see from the issues that SWIG 3 is required, so I updated SWIG with brew:
`brew install SWIG`
and I added it to my path in ~/.bashrc:
`export PATH="/usr/local/Cellar/swig/3.0.12/bin:$PATH"`
```
swig -version

SWIG Version 3.0.12
Compiled with clang++ [x86_64-apple-darwin16.3.0]
Configured options: +pcre
```

then `make python` again. The installation runs without error, but when I try to use the package:
```
>>> import ortools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ortools
```

ortools-examples does appear to be recognized by pip:
```
certifi (2017.7.27.1)
ortools-examples (6.3.4431)
pip (9.0.1)
setuptools (36.3.0)
wheel (0.29.0)
```

I have not been able to get this to work with python 3.5 or 3.6 either. Any suggestions?

**Comment by bendichter** [comment]
issue resolved by following https://github.com/google/or-tools/issues/63#issuecomment-170759237
