### ISSUE TITLE
make rcc EX use C# compiler instead of C++ one

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#619]
# Description
When using EX variable in a make call, C# compiler is used to compile even if it's a C++ example !

# Protocol
```sh
> make rcc EX=examples\cpp\tsp.cc
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin\Roslyn\csc.exe" /keyfile:"bin\\or-tools.snk " /target:exe /debug /out:bin\\tsp.exe /platform:x64 /lib:bin /r:Google.OrTools.dll /r:Google.Protobuf.dll examples\cpp\tsp.cc
Microsoft (R) Visual C# Compiler version 2.6.0.62329 (5429b35d)
Copyright (C) Microsoft Corporation. All rights reserved.

examples\cpp\tsp.cc(28,2): error CS1024: Preprocessor directive expected
[...]
examples\cpp\tsp.cc(163,1): error CS1022: Type or namespace definition, or end-of-file expected
make: *** [bin\\tsp.exe] Error 1
```

# Workaround
```sh
> make bin/tsp.exe
...
> bin\tsp.exe
...
```

**Comment by jimcarst** [comment]
Hi! Thanks for taking a look at this. How do I get this fix working on my machine so I can stop using the work-around?

**Comment by olegshirokikh** [comment]
@Mizux thanks for taking care of this - however, it's still not possible to follow the Getting Started tutorial on https://developers.google.com/optimization/introduction/cpp

Could you please advice how to make the `make rcc EX=simple_program.cc` work with the binary C++ distribution on Windows? (probably editing the shipped Makefile)?

Thanks!

**Comment by Mizux** [comment]
Hi, did you us the last binary archive ?

**Comment by olegshirokikh** [comment]
@Mizux Thanks for the quick response - it did work with v6.9 if I put my prog in `example/cpp/` dir and use `c:\or-tools>tools\make.exe rcc EX=examples\cpp\simple_program.cc`

Just FYI, the official https://developers.google.com/optimization/install/cpp/windows page still points to v6.7, so probably some other people might face the same issue.

Thanks!
