### ISSUE TITLE
Error in installing and calling ortools

### ISSUE THREAD

**Issue by oroojlooy** [google/or-tools#499]
I tried to install ortools as mentioned here,
But I get this error when call `python setup.py install --user`:

`python setup.py install --user
running install
running bdist_egg
running egg_info
writing requirements to ortools_examples.egg-info/requires.txt
writing ortools_examples.egg-info/PKG-INFO
writing top-level names to ortools_examples.egg-info/top_level.txt
writing dependency_links to ortools_examples.egg-info/dependency_links.txt
reading manifest file 'ortools_examples.egg-info/SOURCES.txt'
writing manifest file 'ortools_examples.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install

creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ortools_examples.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/ortools_examples-6.4.4495-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ortools_examples-6.4.4495-py2.7.egg
Removing /root/.local/lib/python2.7/site-packages/ortools_examples-6.4.4495-py2.7.egg
Copying ortools_examples-6.4.4495-py2.7.egg to /root/.local/lib/python2.7/site-packages
ortools-examples 6.4.4495 is already the active version in easy-install.pth

Installed /root/.local/lib/python2.7/site-packages/ortools_examples-6.4.4495-py2.7.egg
Processing dependencies for ortools-examples==6.4.4495
Searching for ortools==6.4.4495
Reading https://pypi.python.org/simple/ortools/
No local packages or working download links found for ortools==6.4.4495
error: Could not find suitable distribution for Requirement.parse('ortools==6.4.4495')
`

Instead, I installed with pip and I can import ortools, but the problem is that when I call it in any code I am getting:

Traceback (most recent call last):
  File "ortools.py", line 8, in <module>
    import ortools
  File "/home/afo214/tensorflow/vrp/stochastic_vrp/src/vrp-pointer/ortools.py", line 16, in <module>
    from ortools.constraint_solver import pywrapcp
ImportError: No module named constraint_solver

Would you mind let me know how I can resolve this problem?

**Comment by lperron** [comment]
Please use pip install ortools with a recent version of pip (>= 9.0.1)

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-10 16:57 GMT+00:00 afshin67 <notifications@github.com>:

**Comment by lperron** [comment]
I misread the end of your mail. Can you tell me which platform you are
using?
Can you make sure you installed 6.4 with pip?

--Laurent

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-10 20:51 GMT+00:00 Laurent Perron <lperron@google.com>:

**Comment by afshin67** [comment]
I have pip 9.0.1 on my Debian, 
I tried same procedure on UBUNTU 16.04 and same error occurred. 
I also downloaded the source code from git and ran the makes, in make python I get:

....
swig -I. -c++ -python  -o ortools/gen/ortools/constraint_solver/constraint_solver_python_wrap.cc -module pywrapcp ./ortools/constraint_solver/python/routing.i
ortools/constraint_solver/constraint_solver.h:267: Warning 325: Nested struct not currently supported (IntegerCastInfo ignored)
ortools/constraint_solver/constraint_solver.h:1756: Error: Syntax error in input(3).
makefiles/Makefile.python.mk:166: recipe for target 'ortools/gen/ortools/constraint_solver/pywrapcp.py' failed
make: *** [ortools/gen/ortools/constraint_solver/pywrapcp.py] Error 1

**Comment by lperron** [comment]
Strange, when I run ubuntu 16.04 in my docker image (clean), everything
work fine

root@9272f152dca3:~/or-tools# apt-get install python-pip

Reading package lists... Done

Building dependency tree

Reading state information... Done

The following additional packages will be installed:

  libpython-all-dev python-all python-all-dev python-pip-whl

The following NEW packages will be installed:

  libpython-all-dev python-all python-all-dev python-pip python-pip-whl

0 upgraded, 5 newly installed, 0 to remove and 5 not upgraded.

Need to get 1258 kB of archives.

After this operation, 1873 kB of additional disk space will be used.

Do you want to continue? [Y/n] y

Get:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 libpython-all-dev
amd64 2.7.11-1 [992 B]

Get:2 http://archive.ubuntu.com/ubuntu xenial/main amd64 python-all amd64
2.7.11-1 [978 B]

Get:3 http://archive.ubuntu.com/ubuntu xenial/main amd64 python-all-dev
amd64 2.7.11-1 [1000 B]

Get:4 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64
python-pip-whl all 8.1.1-2ubuntu0.4 [1110 kB]

Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64
python-pip all 8.1.1-2ubuntu0.4 [144 kB]

Fetched 1258 kB in 1s (700 kB/s)

debconf: delaying package configuration, since apt-utils is not installed

Selecting previously unselected package libpython-all-dev:amd64.

(Reading database ... 27563 files and directories currently installed.)

Preparing to unpack .../libpython-all-dev_2.7.11-1_amd64.deb ...

Unpacking libpython-all-dev:amd64 (2.7.11-1) ...

Selecting previously unselected package python-all.

Preparing to unpack .../python-all_2.7.11-1_amd64.deb ...

Unpacking python-all (2.7.11-1) ...

Selecting previously unselected package python-all-dev.

Preparing to unpack .../python-all-dev_2.7.11-1_amd64.deb ...

Unpacking python-all-dev (2.7.11-1) ...

Selecting previously unselected package python-pip-whl.

Preparing to unpack .../python-pip-whl_8.1.1-2ubuntu0.4_all.deb ...

Unpacking python-pip-whl (8.1.1-2ubuntu0.4) ...

Selecting previously unselected package python-pip.

Preparing to unpack .../python-pip_8.1.1-2ubuntu0.4_all.deb ...

Unpacking python-pip (8.1.1-2ubuntu0.4) ...

Setting up libpython-all-dev:amd64 (2.7.11-1) ...

Setting up python-all (2.7.11-1) ...

Setting up python-all-dev (2.7.11-1) ...

Setting up python-pip-whl (8.1.1-2ubuntu0.4) ...

Setting up python-pip (8.1.1-2ubuntu0.4) ...

root@9272f152dca3:~/or-tools# pip install ortools

Collecting ortools

  Downloading ortools-6.5.4527-cp27-cp27mu-manylinux1_x86_64.whl (8.0MB)

    100% |################################| 8.0MB 210kB/s

Collecting protobuf==3.3.0 (from ortools)

  Downloading protobuf-3.3.0-cp27-cp27mu-manylinux1_x86_64.whl (5.7MB)

    100% |################################| 5.7MB 275kB/s

Requirement already satisfied (use --upgrade to upgrade): six>=1.9 in
/usr/lib/python2.7/dist-packages (from protobuf==3.3.0->ortools)

Requirement already satisfied (use --upgrade to upgrade): setuptools in
/usr/lib/python2.7/dist-packages (from protobuf==3.3.0->ortools)

Installing collected packages: protobuf, ortools

Successfully installed ortools-6.5.4527 protobuf-3.3.0

You are using pip version 8.1.1, however version 9.0.1 is available.

You should consider upgrading via the 'pip install --upgrade pip' command.

root@9272f152dca3:~/or-tools# python examples/python/hidato_table.py


----- Solving problem 1 -----


Initial game (3 x 3)

  6  .  9

  .  2  8

  1  .  .


Solution 1:

  6  7  9

  5  2  8

  1  4  3


solutions : 1

failures  : 0

branches  : 0

wall time : 0


----- Solving problem 2 -----


Initial game (7 x 7)

  . 44 41  .  .  .  .

  . 43  . 28 29  .  .

  .  1  .  .  . 33  .

  .  2 25  4 34  . 36

 49 16  . 23  .  .  .

  . 19  .  . 12  7  .

  .  .  . 14  .  .  .


Solution 1:

 45 44 41 40 39 30 31

 46 43 42 28 29 38 32

 47  1  3 26 27 33 37

 48  2 25  4 34 35 36

 49 16 24 23  5  6  8

 17 19 15 22 12  7  9

 18 20 21 14 13 11 10


solutions : 1

failures  : 1

branches  : 2

wall time : 4


----- Solving problem 3 -----


Initial game (5 x 5)

  .  . 20  .  .

  .  .  . 16 18

 22  . 15  .  .

 23  .  1 14 11

  . 25  .  . 12


Solution 1:

  6  7 20 19 17

  5 21  8 16 18

 22  4 15  9 10

 23  3  1 14 11

 24 25  2 13 12


solutions : 1

failures  : 9

branches  : 18

wall time : 1


----- Solving problem 4 -----


Initial game (5 x 5)

  .  .  .  . 14

  . 18 12  .  .

  .  . 17  4  5

  .  .  7  .  .

  9  8 25  1  .


Solution 1:

 21 20 19 13 14

 22 18 12 16 15

 23 11 17  4  5

 10 24  7  6  3

  9  8 25  1  2


solutions : 1

failures  : 1

branches  : 2

wall time : 1


----- Solving problem 5 -----


Initial game (6 x 6)

  . 26  .  .  . 18

  .  . 27  .  . 19

 31 23  .  . 14  .

  . 33  8  . 15  1

  .  .  .  5  .  .

 35 36  . 10  .  .


Solution 1:

 25 26 29 28 20 18

 24 30 27 21 17 19

 31 23 22 13 14 16

 32 33  8 12 15  1

 34  7  9  5 11  2

 35 36  6 10  4  3


Solution 2:

 25 26 29 28 20 18

 24 30 27 21 17 19

 31 23 22 13 14 16

 32 33  8 12 15  1

 34  7  9  5 11  3

 35 36  6 10  4  2


solutions : 2

failures  : 1

branches  : 4

wall time : 2


----- Solving problem 6 -----


Initial game (8 x 8)

 64  .  .  .  .  .  .  .

  1 63  . 59 15 57 53  .

  .  4  . 14  .  .  .  .

  3  . 11  . 20 19  . 50

  .  .  .  . 22  . 48 40

  9  .  . 32 23  .  . 41

 27  .  .  . 36  . 46  .

 28 30  . 35  .  .  .  .


Solution 1:

 64 62 61 60 58 56 55 54

  1 63  5 59 15 57 53 52

  2  4  6 14 16 17 18 51

  3  7 11 13 20 19 49 50

  8 10 12 24 22 21 48 40

  9 26 25 32 23 47 39 41

 27 29 31 33 36 38 46 42

 28 30 34 35 37 45 44 43


solutions : 1

failures  : 4

branches  : 8

wall time : 8

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-10 22:13 GMT+00:00 afshin67 <notifications@github.com>:

**Comment by lperron** [comment]
Furthermore,

When I run a clean build on ubuntu 16.04, it works fine.

Here are the commands it runs: (from tools/docker/ubuntu-16.04-dockerfile)

apt-get update

apt-get -y install git autoconf libtool zlib1g-dev gawk g++ curl cmake
subversion make mono-complete swig lsb-release python-dev default-jdk twine
python-setuptools python-six python3-setuptools python3-dev python-wheel
python3-wheel

git clone; make third_party; make all

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-10 22:13 GMT+00:00 afshin67 <notifications@github.com>:

**Comment by afshin67** [comment]
Thanks, 
I did not have some of the mentioned packages. Installed them and did make clean and make all is on the way. I'll keep you posted,

**Comment by afshin67** [comment]
I got this error:
ortools/constraint_solver/constraint_solver.h:267: Warning 325: Nested struct not currently supported (IntegerCastInfo ignored)
ortools/constraint_solver/constraint_solver.h:1756: Error: Syntax error in input(3).
makefiles/Makefile.python.mk:166: recipe for target 'ortools/gen/ortools/constraint_solver/pywrapcp.py' failed
make: *** [ortools/gen/ortools/constraint_solver/pywrapcp.py] Error 1

**Comment by lperron** [comment]
Can you run swig -version

I get 3.0.8 on my image.

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-10 23:03 GMT+00:00 afshin67 <notifications@github.com>:

**Comment by afshin67** [comment]
SWIG Version 2.0.12
I'll update and re-make again
Thanks

**Comment by lperron** [comment]
BTW, I also tried the pip install ortools, and it worked perfectly.

sudo apt-get install python-pip

pip install ortools



Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-10 23:52 GMT+00:00 afshin67 <notifications@github.com>:

**Comment by afshin67** [comment]
The error of `make python` is resolved after updating swig. But it got another error:

 make all 
cd dependencies/sources/protobuf-3.3.0/java && \
  ../../../install/bin/protoc --java_out=core/src/main/java -I../src \
  ../src/google/protobuf/descriptor.proto
cd dependencies/sources/protobuf-3.3.0/java/core/src/main/java && /usr/lib/jvm/java-6-openjdk-amd64/bin/javac com/google/protobuf/*java
/bin/sh: 1: /usr/lib/jvm/java-6-openjdk-amd64/bin/javac: not found
makefiles/Makefile.third_party.unix.mk:244: recipe for target 'dependencies/install/lib/protobuf.jar' failed
make: *** [dependencies/install/lib/protobuf.jar] Error 127

BTW, it finished processing `make python`, and now I can run ` python examples/python/hidato_table.py`. But, still I cannot run my code and I am getting:

python /home/afo214/tensorflow/vrp/stochastic_vrp/src/vrp-pointer/ortools.py
Traceback (most recent call last):
  File "/home/afo214/tensorflow/vrp/stochastic_vrp/src/vrp-pointer/ortools.py", line 8, in <module>
    import ortools
  File "/home/afo214/tensorflow/vrp/stochastic_vrp/src/vrp-pointer/ortools.py", line 16, in <module>
    from ortools.constraint_solver import pywrapcp
ImportError: No module named constraint_solver

**Comment by lperron** [comment]
OK, likely a problem with java not detected correctly.

For the ortools.py, if you build from source, you need to add
PYTHONPATH=<path_to_ortools> before running python

You can check the rpy target in makefiles/Makefile.python.mk

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2017-10-11 1:10 GMT+00:00 afshin67 <notifications@github.com>:

**Comment by afshin67** [comment]
I'll figure the permission out,
Thanks

**Comment by gunners009** [comment]
Hi
I am using Jupyter on win 8 Python 2.7
I have already installed ortools
Checked it in Python sitepackage folder. But when I call 

from ortools .graph import pywrapgraph

It gives me error that there is no module -pywrapgraph
But in the folder the pywrapgraph.py, .yc and .pyd files are present.
