### ISSUE TITLE
Google OR tools not functioning

### ISSUE THREAD

**Issue by ankitgupta0310** [google/or-tools#1335]
Dear all, 

Recently, due to my anaconda not working, I had re-installed the software for spyder to function again. My python programs were working before with the help of Google OR tools, but after I installed the tools again, I am getting the following error:

```
>    from ortools.constraint_solver import pywrapcp

  File "C:\Users\ankit\AppData\Roaming\Python\Python27\site-packages\ortools\constraint_solver\pywrapcp.py", line 2530, in <module>
    class IntVarContainer(_object):

  File "C:\Users\ankit\AppData\Roaming\Python\Python27\site-packages\ortools\constraint_solver\pywrapcp.py", line 2560, in IntVarContainer
    __swig_destroy__ = _pywrapcp.delete_IntVarContainer

AttributeError: 'module' object has no attribute 'delete_IntVarContainer'
```

I was previously working with ortools==7.0b6150, but when I pip install this specific version, it is still giving me an error. 

Any help would be appreciated.

**Comment by lperron** [comment]
can you make sure everything was properly deleted, then reinstall ortools ?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 6 juin 2019 à 16:48, ankitgupta0310 <notifications@github.com> a
écrit :

**Comment by ankitgupta0310** [comment]
Dear @lperron ,

Thank you for your response! When I delete ortools, I get this error:
```
Uninstalling ortools-7.0b6150:
  Would remove:
    c:\users\ankit\appdata\roaming\python\python27\site-packages\ortools-7.0b6150.dist-info\*
    c:\users\ankit\appdata\roaming\python\python27\site-packages\ortools\*
Proceed (y/n)? y
  Successfully uninstalled ortools-7.0b6150
Exception:
Traceback (most recent call last):
  File "C:\Users\ankit\Anaconda2\lib\site-packages\pip\_internal\cli\base_command.py", line 179, in main
    status = self.run(options, args)
  File "C:\Users\ankit\Anaconda2\lib\site-packages\pip\_internal\commands\uninstall.py", line 78, in run
    uninstall_pathset.commit()
  File "C:\Users\ankit\Anaconda2\lib\site-packages\pip\_internal\req\req_uninstall.py", line 412, in commit
    self._moved_paths.commit()
  File "C:\Users\ankit\Anaconda2\lib\site-packages\pip\_internal\req\req_uninstall.py", line 263, in commit
    save_dir.cleanup()
  File "C:\Users\ankit\Anaconda2\lib\site-packages\pip\_internal\utils\temp_dir.py", line 83, in cleanup
    rmtree(self.path)
  File "C:\Users\ankit\Anaconda2\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Users\ankit\Anaconda2\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "C:\Users\ankit\Anaconda2\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Users\ankit\Anaconda2\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Users\ankit\Anaconda2\lib\site-packages\pip\_internal\utils\misc.py", line 121, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Users\ankit\Anaconda2\lib\shutil.py", line 270, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\ankit\Anaconda2\lib\shutil.py", line 275, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Users\ankit\Anaconda2\lib\site-packages\pip\_internal\utils\misc.py", line 133, in rmtree_errorhandler
    func(path)
WindowsError: [Error 5] Access is denied: 'c:\\users\\ankit\\appdata\\roaming\\python\\python27\\site-packages\\~.tools\\constraint_solver\\_pywrapcp.pyd'
```

I don't understand why this exception is occuring

**Comment by lperron** [comment]
so process is locking the file
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 6 juin 2019 à 16:58, ankitgupta0310 <notifications@github.com> a
écrit :

**Comment by ankitgupta0310** [comment]
Dear @lperron,

What does that mean? And how can that be changed? 

Thanks a lot

**Comment by ankitgupta0310** [comment]
Dear @lperron,

Thanks for your response, what does that mean? and how can that be changed?

**Comment by lperron** [comment]
Sorry, this is not a ortools issue.
Search is your best friend.
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00



Le jeu. 6 juin 2019 à 17:06, ankitgupta0310 <notifications@github.com> a
écrit :
