### ISSUE TITLE
9.8 fails to build with abseil-20240116.0: error: nested name specifier 'LogSeverity::' for declaration does not refer into a class, class template or class template partial specialization

### ISSUE THREAD

**Issue by yurivict** [google/or-tools#4074]
**What version of OR-Tools and what language are you using?**
Version: 9.8

**What did you do?**
regular build

**What did you see instead?**
```
In file included from /usr/ports/math/or-tools/work/or-tools-9.8/ortools/algorithms/dynamic_permutation.cc:14: 
In file included from /usr/ports/math/or-tools/work/or-tools-9.8/ortools/algorithms/dynamic_permutation.h:22:
In file included from /usr/ports/math/or-tools/work/or-tools-9.8/ortools/base/logging.h:21:
/usr/local/include/absl/base/log_severity.h:92:36: error: nested name specifier 'LogSeverity::' for declaration does not refer into a class, class template or class template partial specialization 
static constexpr absl::LogSeverity kLogDebugFatal = absl::LogSeverity::kError;
                                   ^~~~~~~~~~~~~~
/usr/ports/math/or-tools/work/or-tools-9.8/ortools/base/logging.h:18:37: note: expanded from macro 'kLogDebugFatal'
#define kLogDebugFatal LogSeverity::kError
                       ~~~~~~~~~~~~~^                                   
```

**Anything else we should know about your project / environment**
FreeBSD 14.0
clang-16

**Comment by lperron** [comment]
yes. Not way it can work as I had to implement it because it was not release.
The main branch supports it. But I have big issues with the code. Debugging.

Thanks
