### ISSUE TITLE
Fuzztest build is borken

### ISSUE THREAD

**Issue by Mizux** [google/or-tools#4768]
**What version of OR-Tools and what language are you using?**
Version: main
Language: C++

When bumping abseil-cpp to 20250814.0 had to bump Fuzztest to 2025-08-05 to avoid compilation error but this release seems broken...

trace: 
CMake: https://github.com/google/or-tools/actions/runs/17438949189/job/49516465043

note: bazel avoid it since or-tools don't depend on `@fuzztest//fuzztest/internal:subprocess`

ref:
* https://github.com/google/fuzztest/issues/1845

**Comment by kayo09** [comment]
Direction for noobs like me to reproduce this locally:
```sh
> mkdir or && cd or
> git clone https://github.com/google/or-tools.git
> cd or-tools
> git checkout main
> cd ..
> git clone https://github.com/abseil/abseil-cpp.git && cd abseil-cpp
> git checkout 20250814.0
> cd .. ; git clone https://github.com/google/fuzztest.git
> cd fuzztest && git checkout 2025-08-05
> cd ..
> mkdir fuzztest-repro && cd fuzztest-repro
> touch CMakeLists.txt
```
CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.16)
project(FuzztestSubprocessRepro LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Point to your Abseil checkout
set(ABSL_ROOT "../abseil-cpp")

# Add Abseil
add_subdirectory(${ABSL_ROOT} ${CMAKE_BINARY_DIR}/abseil-build EXCLUDE_FROM_ALL)

# Path to fuzztest sources
set(FUZZTEST_SRC "../fuzztest")

# Target: build just subprocess.cc
add_executable(subprocess_test
    ${FUZZTEST_SRC}/fuzztest/internal/subprocess.cc
)

target_include_directories(subprocess_test PRIVATE
    ${FUZZTEST_SRC}
)

target_link_libraries(subprocess_test PRIVATE
    absl::base
    absl::strings
    absl::time
    absl::flat_hash_map
)
```
```sh
> mkdir build && cd build
> cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
> cmake --build . -j$(sysctl -n hw.ncpu)
```
**Note**: Why was this needed? Cause doing this without a CMakeLists.txt fails to reproduce the issue since Fuzztest keeps building with its own vendored Abseil (instead of local/ system)
