### ISSUE TITLE
Version 9.8 fails to build with abseil-20230125.3: error: no matching function for call to 'StrCat'

### ISSUE THREAD

**Issue by yurivict** [google/or-tools#4070]
**What version of OR-Tools and what language are you using?**
Version: 9.8
Language: n/a

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
n/a

**What operating system (Linux, Windows, ...) and version?**
FreeBSD 14.0

**What did you do?**
regular build

**What did you expect to see**
n/a

**What did you see instead?**
```
/usr/ports/math/or-tools/work/or-tools-9.8/ortools/sat/cuts.cc:70:24: error: no matching function for call to 'StrCat'
  std::string result = absl::StrCat("CutData rhs=", rhs, "\n");
                       ^~~~~~~~~~~~
/usr/local/include/absl/strings/str_cat.h:388:34: note: candidate function not viable: no known conversion from 'const absl::int128' to 'const AlphaNum' for 2nd argument
ABSL_MUST_USE_RESULT std::string StrCat(const AlphaNum& a, const AlphaNum& b,
                                 ^
/usr/local/include/absl/strings/str_cat.h:387:34: note: candidate function not viable: requires 2 arguments, but 3 were provided
ABSL_MUST_USE_RESULT std::string StrCat(const AlphaNum& a, const AlphaNum& b);
                                 ^
/usr/local/include/absl/strings/str_cat.h:390:34: note: candidate function not viable: requires 4 arguments, but 3 were provided
ABSL_MUST_USE_RESULT std::string StrCat(const AlphaNum& a, const AlphaNum& b,
                                 ^
/usr/local/include/absl/strings/str_cat.h:383:41: note: candidate function not viable: requires single argument 'a', but 3 arguments were provided
ABSL_MUST_USE_RESULT inline std::string StrCat(const AlphaNum& a) {
                                        ^
/usr/local/include/absl/strings/str_cat.h:381:41: note: candidate function not viable: requires 0 arguments, but 3 were provided
ABSL_MUST_USE_RESULT inline std::string StrCat() { return std::string(); }
                                        ^
/usr/local/include/absl/strings/str_cat.h:395:41: note: candidate function template not viable: requires at least 5 arguments, but 3 were provided
ABSL_MUST_USE_RESULT inline std::string StrCat( 
                                        ^
/usr/local/include/absl/strings/str_cat.h:400:8: error: no viable conversion from 'const absl::int128' to 'const AlphaNum'
       static_cast<const AlphaNum&>(args).Piece()...});
       ^                            ~~~~
/usr/ports/math/or-tools/work/or-tools-9.8/ortools/sat/cuts.cc:1997:16: note: in instantiation of function template specialization 'absl::StrCat<absl::int128, char[8], int, char[6], int, char[6], int>' requested here      
  return absl::StrCat("#in:", in_flow.size(), " #out:", out_flow.size(),
               ^
/usr/local/include/absl/strings/str_cat.h:255:3: note: candidate constructor not viable: no known conversion from 'const absl::int128' to 'int' for 1st argument
  AlphaNum(int x)  // NOLINT(runtime/explicit)
  ^
/usr/local/include/absl/strings/str_cat.h:259:3: note: candidate constructor not viable: no known conversion from 'const absl::int128' to 'unsigned int' for 1st argument
  AlphaNum(unsigned int x)  // NOLINT(runtime/explicit) 
  ^
/usr/local/include/absl/strings/str_cat.h:263:3: note: candidate constructor not viable: no known conversion from 'const absl::int128' to 'long' for 1st argument
  AlphaNum(long x)  // NOLINT(*)
  ^
/usr/local/include/absl/strings/str_cat.h:267:3: note: candidate constructor not viable: no known conversion from 'const absl::int128' to 'unsigned long' for 1st argument
  AlphaNum(unsigned long x)  // NOLINT(*)
  ^
/usr/local/include/absl/strings/str_cat.h:271:3: note: candidate constructor not viable: no known conversion from 'const absl::int128' to 'long long' for 1st argument
  AlphaNum(long long x)  // NOLINT(*)
  ^
/usr/local/include/absl/strings/str_cat.h:275:3: note: candidate constructor not viable: no known conversion from 'const absl::int128' to 'unsigned long long' for 1st argument
  AlphaNum(unsigned long long x)  // NOLINT(*)
  ^
/usr/local/include/absl/strings/str_cat.h:280:3: note: candidate constructor not viable: no known conversion from 'const absl::int128' to 'float' for 1st argument
  AlphaNum(float f)  // NOLINT(runtime/explicit)
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

**Comment by Mizux** [comment]
Confirmed v9.8 has be built against abseil-cpp 20230802.1

https://github.com/google/or-tools/blob/43e400c4f2749268d6a53d39be8f019906fd19c9/cmake/dependencies/CMakeLists.txt#L84-L85
