### ISSUE TITLE
AttributeError: 'ortools.sat.python.cp_model_helper.ConstraintProto' object has no attribute 'Clear'

### ISSUE THREAD

**Issue by disonvon** [google/or-tools#5069]
**What version of OR-Tools and what language are you using?**
Version: 9.15.6755
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
CP-SAT
**What operating system (Linux, Windows, ...) and version?**
Linux
**What did you do?**
After i upgrade ortools to 9.15 get attribute error:

self.model.Proto().constraints[i].Clear()
AttributeError: 'ortools.sat.python.cp_model_helper.ConstraintProto' object has no attribute 'Clear'

**What did you expect to see**
The Clear() seems to be deleted? which alternative do we have?

I see we have clear specific type of constraints, in my case, i want to clear/delete specific index constraint

**Comment by lperron** [comment]
duplicate of:
* #5018 

Linked to:
* #5038

**Comment by lperron** [comment]
I have added clear() after the release
