### ISSUE TITLE
Cannot compile on v7.0

### ISSUE THREAD

**Issue by 326623** [google/or-tools#1173]
Both gcc (`Ubuntu 5.4.0-6ubuntu1~16.04.11`) `5.4.0 20160609` and
clang version `6.0.0-1ubuntu2~16.04.1` (`tags/RELEASE_600/final`) failed to compile and report this error.

```sh
or-tools/ortools/linear_solver/linear_solver.h:731:13: error: use of
      overloaded operator '<<' is ambiguous (with operand types 'std::ostream' (aka 'basic_ostream<char>') and
      'const absl::string_view')
```

**Comment by lperron** [comment]
We support ubuntu stock 16.04 and up.
Which version are you using?
Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by Mizux** [comment]
Please give us the command you run.

**Comment by 326623** [comment]
Sorry... My bad. I got confused. It seems that I have installed previous version of ortools in /usr/local/include. After I renamed it, it compiled successfully. Sorry again...

**Comment by 326623** [comment]
By the way, will you guys support parallel CMake build of Cbc in the future? 
Currently, I have to do some hacking to get there.

**Comment by Mizux** [comment]
What do you mean by parallel CMake build of Cbc ?

note: I'm currently migrating my CMake support from Cbc svn mono archive to splitted coin-or github fork.
see: #1116

**Comment by 326623** [comment]
Sorry for the ambiguity. By **parallel** I mean like the original flag --enable-cbc-parallel in the configure file.
I see. Will that support the full feature of coinor-cbc(parallel support)? 
Thanks for the great work!
