### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by chixsy** [google/or-tools#626]
Hello, 
I was following the installation for OR Tools (6.4) from the binary, but ran into a problem. 
make third_party goes through fine, but "make python" throws an error - 

./ortools/sat/cp_model_solver.cc:1829:5: error: return type 'const IntType<[2 * ...]>' must match previous return type 'IntType<[2 * ...]>' when lambda expression has unspecified explicit return type

OSX 10.11.6
Python 3.5

Thanks !

**Comment by lperron** [comment]
Can you try with 6.7?

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by chixsy** [comment]
Hello Laurent,
Thanks for the suggestion. I did try with 6.7.1, following all procedures -  but ended up with the same error - pleas find attached a screenshot.

<img width="1280" alt="screen shot 2018-03-20 at 10 08 25 am" src="https://user-images.githubusercontent.com/33178732/37663269-dc3023ac-2c26-11e8-8b09-391cfe974119.png">

**Comment by lperron** [comment]
Which compiler are you using?

It compiles fine with clang-900.0.39.2 (xcode command line utils).

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00

**Comment by chixsy** [comment]
This is what I have: Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Let me try the version you have and see. I will keep you posted. Thanks
