### ISSUE TITLE
Annotation redifinitions with MiniZinc 2.6.3

### ISSUE THREAD

**Issue by scand1sk** [google/or-tools#3339]
**What version of OR-Tools and what language are you using?**
Version: 9.3 (FlatZinc)
Language: Command-line (flatzinc)

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
FlatZinc for Ubuntu 20.04

**What operating system (Linux, Windows, ...) and version?**
Linux Debian bookworm/sid

**What did you do?**
Configure MiniZincIDE with OR-Tools Flatzinc.

**What did you expect to see**
Solutions to my model

**What did you see instead?**
Error message:
```
[stdlib_ann:441-1.449-9](err:/home/***/MiniZincIDE-2.6.3-bundle-linux-x86_64/share/minizinc/std/stdlib/stdlib_ann.mzn?line=441&column=1):
MiniZinc: type error: function with the same type already defined in /home/***/or-tools_flatzinc_--64bit_v9.3.10502/share/minizinc/redefinitions-2.0.mzn:101.1-106.28
Process finished with non-zero exit code 1.
```
I got this message after I upgraded MiniZinc from 2.6.1 to 2.6.3.
Culprits seem to be redefinition of warm_start annotations in redefinitions-2.0.mzn. Workaround is to comment out these lines.
If am not familiar with MiniZinc redefinitions, but maybe they should be moved to another file, or there is an issue with MiniZinc itself.

**Anything else we should know about your project / environment**

**Comment by Mizux** [comment]
Should be fixed on master: see 
https://github.com/google/or-tools/commit/45c608e371d450a3dbace5462ed7e8cedea251ad
