### ISSUE TITLE
make test_cc fails on Ubuntu 20.04 with v9.3

### ISSUE THREAD

**Issue by ankane** [google/or-tools#3184]
**What version of OR-Tools and what language are you using?**
Version: v9.3
Language: C++

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)** n/a

**What operating system (Linux, Windows, ...) and version?** Ubuntu 20.04

**What did you do?**

```sh
wget https://github.com/google/or-tools/releases/download/v9.3/or-tools_amd64_ubuntu-20.04_v9.3.10497.tar.gz
tar xzf or-tools_amd64_ubuntu-20.04_v9.3.10497.tar.gz
cd or-tools_amd64_ubuntu-20.04_v9.3.10497
make test_cc
```

**What did you expect to see**

No error

**What did you see instead?**

```sh
CC = cc
CC_BIN = /usr/bin/cc
CXX = g++
CXX_BIN = /usr/bin/g++
CXXFLAGS = -fPIC -std=c++17 -O4 -DNDEBUG -Iinclude -I. -DARCH_K8 -Wno-deprecated -DUSE_BOP -DUSE_GLOP -DUSE_PDLP -DUSE_CBC -DUSE_CLP -DUSE_SCIP
LDFLAGS = -Wl,-rpath,$ORIGIN -Wl,-rpath,$ORIGIN/../lib64 -Wl,-rpath,$ORIGIN/../lib -lz -lrt -lpthread
OR_TOOLS_LNK = -Llib -Llib64 -lortools

make run SOURCE=examples/cpp/simple_knapsack_program.cc
make[1]: Entering directory '/tmp/or-tools_Ubuntu-20.04-64bit_v9.3.10497'
g++ -fPIC -std=c++17 -O4 -DNDEBUG -Iinclude -I. -DARCH_K8 -Wno-deprecated -DUSE_BOP -DUSE_GLOP -DUSE_PDLP -DUSE_CBC -DUSE_CLP -DUSE_SCIP \
 objs/simple_knapsack_program..o \
 -Llib -Llib64 -lortools -Wl,-rpath,"\$ORIGIN" -Wl,-rpath,"\$ORIGIN/../lib64" -Wl,-rpath,"\$ORIGIN/../lib" -lz -lrt -lpthread \
 -o bin/simple_knapsack_program
/usr/bin/ld: lib/libortools.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve()@GLIBCXX_3.4.29'
/usr/bin/ld: lib/libortools.so: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:306: bin/simple_knapsack_program] Error 1
make[1]: Leaving directory '/tmp/or-tools_Ubuntu-20.04-64bit_v9.3.10497'
make: *** [Makefile:275: test_cc] Error 2
```

Make sure you include information that can help us debug (full error message, model Proto).

**Anything else we should know about your project / environment**

I think the library may have been compiled against a newer GLIBCXX (3.4.29). When running:

```sh
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
```

on Ubuntu 20.04, the latest version returned is `GLIBCXX_3.4.28`.

**Comment by Mizux** [comment]
Actually we should use a C++20 compiler so I use gcc11 for ppa which bump the GLIBCXX 

https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/tools/docker/amd64/ubuntu-20.04.Dockerfile#L15-L24

**Comment by ankane** [comment]
Also noticed two more things:

1. When updating the Ruby library to 9.3, linking with `libortools.so` works, but when running the program, it looks for `libortools.so.9` (which wasn't the case previously). I think it may be due to `SONAME`.

```sh
objdump -p lib/libortools.so | grep SONAME
  SONAME               libortools.so.9
```

2. There are 3 identical copies of the shared library (`libortools.so`, `libortools.so.9`, `libortools.so.9.3.10497`) in the `lib` directory. It may be better to use symlinks for two.

**Comment by Mizux** [comment]
1. Yes since we are using CMake based build now, so we have soname support
https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/cmake/cpp.cmake#L108-L118

2. when building there are effectively symlink BUT our archive recipe replace all symlinks by copy of the library also python, java, .net only embed the libortools.so.9 (since bridge library depend on it) so it was easier to keep it as it  than breaking everything

BTW I will try to fix it for the next release

**Comment by Mizux** [comment]
ToDo List:
* [ ] Create table for each Ubuntu gcc default max GLIBCXX availabe and same after bumping compiler
* [ ] Fix symlinks in archive

**Comment by ankane** [comment]
Thanks @Mizux, will use `libortools.so.9` for the gem.

Also, just saw your question about testing. Happy to test anything around this.

**Comment by Mizux** [comment]
Fixed with
[or-tools_amd64_ubuntu-20.04_v9.3.10502.tar.gz](https://github.com/google/or-tools/releases/download/v9.3/or-tools_amd64_ubuntu-20.04_v9.3.10502.tar.gz)
and
[or-tools_amd64_flatzinc_ubuntu-20.04_v9.3.10502.tar.gz](https://github.com/google/or-tools/releases/download/v9.3/or-tools_amd64_flatzinc_ubuntu-20.04_v9.3.10502.tar.gz)

**Comment by ankane** [comment]
Thanks @Mizux, working great! Just pushed a new release of the Ruby gem.

**Comment by GhasseneBouachir** [comment]
Still not working with the actual official binary version in the or-tools site. Thanks @Mizux, this version working great. 
Plz put the correct version(without BUG) in the official website.
