### ISSUE TITLE
SetVisitType signature change with lack of documentation

### ISSUE THREAD

**Issue by famagusta** [google/or-tools#3746]
**What version of OR-Tools and what language are you using?**
Version: v8.2.8710 (upgrading from v7.5.7466)
Language: Python

**Which solver are you using (e.g. CP-SAT, Routing Solver, GLOP, BOP, Gurobi)**
Routing Solver

**What operating system (Linux, Windows, ...) and version?**
Linux (Python docker image - python:3.7.10 on Debian GNU/Linux 10 (buster))

**What did you do?**
1. ```py
   routing.SetVisitType(routing_index_manager.NodeToIndex(int(idx)), int(row[type_col]))
   ```

failed with error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/unittest/mock.py", line 1256, in patched
    return func(*args, **keywargs)
  File "/app/order_allocation/allocation_engine/tests/test_batched_allocation.py", line 177, in test_mkt_allocation
    mktplc_fleet_eligible_seller_ids=[2835])
  File "/usr/local/lib/python3.7/site-packages/newrelic/api/function_trace.py", line 154, in literal_wrapper
    return wrapped(*args, **kwargs)
  File "/app/order_allocation/allocation_engine/batched_allocation_helper.py", line 1636, in allocate_orders
    time_horizon=node_df['tw_close'].max())
  File "/usr/local/lib/python3.7/site-packages/newrelic/api/function_trace.py", line 154, in literal_wrapper
    return wrapped(*args, **kwargs)
  File "/app/order_allocation/allocation_engine/helpers/routing.py", line 519, in solve_routing_problem_v2
    in df[df[type_col].notnull()].iterrows()]
  File "/app/order_allocation/allocation_engine/helpers/routing.py", line 518, in <listcomp>
    [routing.SetVisitType(routing_index_manager.NodeToIndex(int(idx)), int(row[type_col])) for idx, row
TypeError: SetVisitType() missing 1 required positional argument: 'type_policy'
```

The above was working fine in v7.5.7466.

I can't seem to find any documentation on how/when to set the type_policy. Release notes had no mention.

**Comment by Mizux** [comment]
https://github.com/google/or-tools/blob/11f50e00a8086e32794b93f82fa21c968ea14276/ortools/constraint_solver/routing.h#L928-L958

**Comment by famagusta** [comment]
Is there any example on how to set this correctly? We were not required to set such a value in v7.5
The examples section on the ortools page (https://developers.google.com/optimization/examples)
doesn't have any relevant examples.

**Comment by Mizux** [comment]
Not yet the only c++ unit test we have is:

```cpp
TEST(VisitTypesTest, SingleNodesOfTypeTest) {
  const int kNumNodes = 3;
  const int kNumVehicles = 1;
  const RoutingIndexManager manager(kNumNodes, kNumVehicles, NodeIndex(0));
  RoutingModel model(manager);

  model.SetVisitType(1, 5, VisitTypePolicy::ADDED_TYPE_REMOVED_FROM_VEHICLE);
  model.SetVisitType(2, 0, VisitTypePolicy::TYPE_ADDED_TO_VEHICLE);
  model.CloseModel();

  EXPECT_EQ(model.GetNumberOfVisitTypes(), 6);
  EXPECT_THAT(model.GetSingleNodesOfType(0), testing::ElementsAre(2));
  EXPECT_THAT(model.GetSingleNodesOfType(5), testing::ElementsAre(1));
  for (int inexisting_type = 1; inexisting_type < 5; inexisting_type++) {
    EXPECT_TRUE(model.GetSingleNodesOfType(inexisting_type).empty());
  }
}

TEST(VisitTypesTest, PairIndicesOfTypeTest) {
  const int kNumNodes = 11;
  const int kNumVehicles = 1;
  const RoutingIndexManager manager(kNumNodes, kNumVehicles, NodeIndex(0));
  RoutingModel model(manager);

  const std::vector<std::pair<std::vector<int64_t>, std::vector<int64_t>>>
      pickup_delivery_nodes = {{{1, 2}, {3}}, {{4, 5}, {6, 7}}, {{8}, {9, 10}}};

  for (const RoutingIndexPair& pickup_deliveries : pickup_delivery_nodes) {
    const RoutingModel::DisjunctionIndex pickup_disjunction(
        model.AddDisjunction(pickup_deliveries.first, RoutingModel::kNoPenalty,
                             /*max_cardinality=*/1));
    const RoutingModel::DisjunctionIndex delivery_disjunction(
        model.AddDisjunction(pickup_deliveries.second, RoutingModel::kNoPenalty,
                             /*max_cardinality=*/1));
    model.AddPickupAndDeliverySets(pickup_disjunction, delivery_disjunction);
  }

  for (int index = 1; index < kNumNodes; index++) {
    model.SetVisitType(index, /*type*/ (index + 1) / 2,
                       VisitTypePolicy::TYPE_SIMULTANEOUSLY_ADDED_AND_REMOVED);
  }
  model.CloseModel();

  // Types go from 0 to 5.
  const int kExpectedNumTypes = 6;
  ASSERT_EQ(model.GetNumberOfVisitTypes(), kExpectedNumTypes);
  const std::vector<std::vector<int>> kExpectedPairIndicesOfType = {
      {}, {0}, {0, 1}, {1}, {1, 2}, {2}};
  for (int type = 0; type < kExpectedPairIndicesOfType.size(); type++) {
    EXPECT_THAT(
        model.GetPairIndicesOfType(type),
        testing::UnorderedElementsAreArray(kExpectedPairIndicesOfType[type]));
  }
}
```
